# Mac-specific configuration
alias parallel-ssh="$(which pssh)"
alias parallel-scp="$(which pscp)"

eval "$(/opt/homebrew/bin/brew shellenv)"

export LC_jason_ventresca=yes
export AWS_jason_ventresca=yes

source $HOME/dotfiles.jason_ventresca/dotfiles/bashrc

# Short of learning how to actually configure OSX, here's a hacky way to use
# GNU manpages for programs that are GNU ones, and fallback to OSX manpages otherwise.
# See https://gist.github.com/quickshiftin/9130153 for more info.
alias man='_() { echo $1; man -M $(brew --prefix)/opt/coreutils/libexec/gnuman $1 1>/dev/null 2>&1;  if [ "$?" -eq 0 ]; then man -M $(brew --prefix)/opt/coreutils/libexec/gnuman $1; else man $1; fi }; _'
